local common = {
    "HitPoints",
    "MaxHitPoints",
    "CollisionDamage",
    "Visible",
    "FlipX",
    "DepthOffset",
    "Mass",
    "Size",
    "SpriteRotation",
}
local schema = {
    [1] = {
        "Damage",
        "MaxFireDelay",
        "FireDelay",
        "ShotSpeed",
        "MoveSpeed",
        "Luck",
        "CanFly",
        "TearHeight",
        "TearRange",
        "TearFallingSpeed",
        "TearFallingAcceleration",
        "HeadFrameDelay",
        "ControlsEnabled",
    },
    [2] = { "FallingAcceleration", "FallingSpeed", "Height", "Rotation", "Scale", "WaitFrames" },
    [3] = {
        "State",
        "FireCooldown",
        "HeadFrameDelay",
        "MoveDirection",
        "ShootDirection",
        "LastDirection",
        "OrbitAngleOffset",
        "OrbitLayer",
        "OrbitSpeed",
    },
    [4] = { "ExplosionDamage", "RadiusMultiplier", "IsFetus" },
    [5] = {
        "AutoUpdatePrice",
        "Charge",
        "OptionsPickupIndex",
        "Price",
        "ShopItemId",
        "State",
        "Timeout",
        "Touched",
        "Wait",
    },
    -- J460 exposes SampleLaser as userdata, not a boolean property.
    -- The native sampling flag and path are already carried by laser_path.
    [7] = {
        "Angle",
        "AngleDegrees",
        "LastAngleDegrees",
        "MaxDistance",
        "Radius",
        "Timeout",
        "LaserLength",
        "Shrink",
        "DisableFollowParent",
        "CurveStrength",
        "GridHit",
    },
    [8] = {
        "Rotation",
        "RotationOffset",
        "Scale",
        "Charge",
        "MaxDistance",
        "PathFollowSpeed",
        "PathOffset",
    },
    [9] = {
        "Height",
        "FallingSpeed",
        "FallingAccel",
        "Scale",
        "Damage",
        "Acceleration",
        "HomingStrength",
        "CurvingStrength",
    },
    [1000] = {
        "State",
        "Timeout",
        "LifeSpan",
        "Rotation",
        "Scale",
        "FallingAcceleration",
        "FallingSpeed",
        "m_Height",
        "MinRadius",
        "MaxRadius",
    },
    npc = { "State", "StateFrame", "I1", "I2", "ProjectileCooldown", "ProjectileDelay", "Scale" },
}
return { common = common, byType = schema }
